apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
  namespace: test-env
spec:
  type: NodePort
  selector:
    app: reddit-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000

